print("################################")
print("#                              #")
print("#  Shareefa Syarvia Yuwandina  #")
print("#       2610817120015          #")
print("#                              #")
print("################################")